### ISSUE TITLE
Need more airhorn

### ISSUE THREAD

**Issue by iansteele** [lrdiv/slack-slashsound#3]
http://www.myinstants.com/instant/dj-airhorn/

I need to feel like i'm in the club

![image](https://cloud.githubusercontent.com/assets/7293973/12356382/09298722-bb68-11e5-82d6-7f3aa92864e6.png)

**Comment by tjb** [comment]
See #4

**Comment by iansteele** [comment]
I miss this guurrrlllls @tylerbobella @lrdiv
